### ISSUE TITLE
pointIndex increment in rotateBy

### ISSUE THREAD

**Issue by bkiers** [bkiers/RotatingCalipers#2]
(bug reported by email)

I think the pointIndex increment should be:

```
pointIndex = (pointIndex + 1) % convexHull.size();
```

Also, I think it might be safer for the `currentAngle` increment to always keep the `currentAngle` in the interval `[0, 360)`:

```
this.currentAngle = (this.currentAngle + angle) % 360;
```

**Comment by kenyee** [comment]
looks like the current code has the pointIndex but is missing the %360?

**Comment by bkiers** [comment]
True, added in https://github.com/bkiers/RotatingCalipers/commit/6ce2e047f53835b50e59e8ab055ebb6ad9cc6d0c
